// import './AlertMessage.story'
// import './DrawerButton.story'
// import './FullButton.story'
// import './RoundedButton.story'
import '../Components/Button/Button.story'
import '../Components/ScreenOnboard/ScreenOnboard.story'
import './StyledText.story'
import '../Components/ScreenLogin/ScreenLogin.story'
import '../Components/ScreenSignup/ScreenSignup.story'
import '../Components/ScreenPin/ScreenPin.story'
import '../Components/ComponentHeader/ComponentHeader.story'
