// RESTAPI
export const RESTAPI_FETCH_ALL = 'RESTAPI_FETCH_ALL';
export const RESTAPI_FETCH_ALL_SUCCESS = 'RESTAPI_FETCH_ALL_SUCCESS';
export const RESTAPI_FETCH_ALL_ERROR = 'RESTAPI_FETCH_ALL_ERROR';

// CHATS
export const CHATS_FETCH_ALL_INPROGRESS = 'CHATS_FETCH_ALL_INPROGRESS';
export const CHATS_FETCH_ALL = 'CHATS_FETCH_ALL';
export const CHATS_FETCH_ALL_SUCCESS = 'CHATS_FETCH_ALL_SUCCESS';
export const CHATS_FETCH_ALL_ERROR = 'CHATS_FETCH_ALL_ERROR';
export const CHATS_JOIN_CONTACT = 'CHATS_JOIN_CONTACT';
export const CHATS_SET_RELOAD = 'CHATS_SET_RELOAD';
export const CHATS_INC_BADGE = 'CHATS_INC_BADGE';
export const CHATS_RESET_BADGE = 'CHATS_RESET_BADGE';

// GROUP
export const GROUP_READ_INPROGRESS = 'GROUP_READ_INPROGRESS';
export const GROUP_CREATE_INPROGRESS = 'GROUP_CREATE_INPROGRESS';
export const GROUP_CREATE_SUCCESS = 'GROUP_CREATE_SUCCESS';
export const GROUP_CREATE_ERROR = 'GROUP_CREATE_ERROR';
export const GROUP_UPDATE_INPROGRESS = 'GROUP_UPDATE_INPROGRESS';
export const GROUP_UPDATE_SUCCESS = 'GROUP_UPDATE_SUCCESS';
export const GROUP_UPDATE_ERROR = 'GROUP_UPDATE_ERROR';
export const GROUP_UPDATE_PICTURE_BY_ID = 'GROUP_UPDATE_PICTURE_BY_ID';
export const GROUP_READ_SUCCESS = 'GROUP_READ_SUCCESS';
export const GROUP_READ_ERROR = 'GROUP_READ_ERROR';
export const GROUP_SET_LAST_MESSAGE = 'GROUP_SET_LAST_MESSAGE';
export const GROUP_RENAME_INPROGRESS = 'GROUP_RENAME_INPROGRESS';
export const GROUP_RENAME_SUCCESS = 'GROUP_RENAME_SUCCESS';
export const GROUP_RENAME_ERROR = 'GROUP_RENAME_ERROR';
export const GROUP_RM_ONE_MEMBER_INPROGRESS = 'GROUP_RM_ONE_MEMBER_INPROGRESS';
export const GROUP_RM_ONE_MEMBER_SUCCESS = 'GROUP_RM_ONE_MEMBER_SUCCESS';
export const GROUP_RM_ONE_MEMBER_ERROR = 'GROUP_RM_ONE_MEMBER_ERROR';
export const GROUP_UPDATE_MEMBER_INPROGRESS = 'GROUP_UPDATE_MEMBER_INPROGRESS';
export const GROUP_UPDATE_MEMBER_SUCCESS = 'GROUP_UPDATE_MEMBER_SUCCESS';
export const GROUP_UPDATE_MEMBER_ERROR = 'GROUP_UPDATE_MEMBER_ERROR';

// COINS
export const COINS_UPSERT_INPROGRESS = 'COINS_UPSERT_INPROGRESS';
export const COINS_UPSERT_SUCCESS = 'COINS_UPSERT_SUCCESS';

// USER
export const USER_UPSERT_INPROGRESS = 'USER_UPSERT_INPROGRESS';
export const USER_UPSERT_SUCCESS = 'USER_UPSERT_SUCCESS';

// USERPROFILE
export const USERPROFILE_UPDATE_INPROGRESS = 'USERPROFILE_UPDATE_INPROGRESS';
export const USERPROFILE_UPDATE_SUCCESS = 'USERPROFILE_UPDATE_SUCCESS';
export const USERPROFILE_UPDATE_PHOTO_INPROGRESS = 'USERPROFILE_UPDATE_PHOTO_INPROGRESS';
export const USERPROFILE_UPDATE_PHOTO_SUCCESS = 'USERPROFILE_UPDATE_PHOTO_SUCCESS';
export const USERPROFILE_UPDATE_ERROR = 'USERPROFILE_UPDATE_ERROR';
export const GROUPPROFILE_RENAME_INPROGRESS = 'GROUPPROFILE_RENAME_INPROGRESS';

//  FILES
export const FILES_UPSERT_INPROGRESS = 'FILES_UPSERT_INPROGRESS';
export const FILES_UPSERT_SUCCESS = 'FILES_UPSERT_SUCCESS';

//  NOTIFICATION
export const NOTIFICATION_PUSH = 'NOTIFICATION_PUSH';
export const NOTIFICATION_FETCH_ALL_INPROGRESS = 'NOTIFICATION_FETCH_ALL_INPROGRESS';
export const NOTIFICATION_FETCH_ALL = 'NOTIFICATION_FETCH_ALL';
export const NOTIFICATION_FETCH_ALL_SUCCESS = 'NOTIFICATION_FETCH_ALL_SUCCESS';
export const NOTIFICATION_FETCH_ALL_ERROR = 'NOTIFICATION_FETCH_ALL_ERROR';
export const NOTIFICATION_INPUTMESSAGE_MODIFICATION = 'NOTIFICATION_INPUTMESSAGE_MODIFICATION';
export const NOTIFICATION_SEND_MESSAGE_SUCCESS = 'NOTIFICATION_SEND_MESSAGE_SUCCESS';
export const NOTIFICATION_SET_RELOAD = 'NOTIFICATION_SET_RELOAD';
export const NOTIFICATION_ON_LESTENING = 'NOTIFICATION_ON_LESTENING';
export const NOTIFICATION_INC_BADGE = 'NOTIFICATION_INC_BADGE';
export const NOTIFICATION_RESET_BADGE = 'NOTIFICATION_RESET_BADGE';
export const NOTIFICATION_INC_LAUNCH_BADGE = 'NOTIFICATION_INC_LAUNCH_BADGE';
export const NOTIFICATION_RESET_LAUNCH_BADGE = 'NOTIFICATION_RESET_LAUNCH_BADGE';
export const NOTIFICATION_ONVALUE_INPROGRESS = 'NOTIFICATION_ONVALUE_INPROGRESS';
export const NOTIFICATION_ONVALUE_DONE = 'NOTIFICATION_ONVALUE_DONE';
export const NOTIFICATION_CONSUME_INPROGRESS = 'NOTIFICATION_CONSUME_INPROGRESS';
export const NOTIFICATION_CONSUME_DONE = 'NOTIFICATION_CONSUME_DONE';
export const NOTIFICATION_PUSH_NEWINCOMING_DONE = 'NOTIFICATION_PUSH_NEWINCOMING_DONE';
export const NOTIFICATION_PUSH_NEWINCOMING_INPROGRESS = 'NOTIFICATION_PUSH_NEWINCOMING_INPROGRESS';
export const NOTIFICATION_POPUP = 'NOTIFICATION_POPUP';

//  CONVERSATION
export const CONVERSATION_SAVE_CONVERSATION = 'CONVERSATION_SAVE_CONVERSATION';
export const CONVERSATION_FETCH_ALL_GROUP_MESSAGE_INPROGRESS = 'CONVERSATION_FETCH_ALL_GROUP_MESSAGE_INPROGRESS';
export const CONVERSATION_FETCH_ALL_GROUP_MESSAGE_DONE = 'CONVERSATION_FETCH_ALL_GROUP_MESSAGE_DONE';
export const CONVERSATION_FETCH_ALL_INPROGRESS = 'CONVERSATION_FETCH_ALL_INPROGRESS';
export const CONVERSATION_FETCH_ALL = 'CONVERSATION_FETCH_ALL';
export const CONVERSATION_FETCH_ALL_SUCCESS = 'CONVERSATION_FETCH_ALL_SUCCESS';
export const CONVERSATION_FETCH_ALL_ERROR = 'CONVERSATION_FETCH_ALL_ERROR';
export const CONVERSATION_INPUTMESSAGE_MODIFICATION = 'CONVERSATION_INPUTMESSAGE_MODIFICATION';
export const CONVERSATION_SEND_MESSAGE_SUCCESS = 'CONVERSATION_SEND_MESSAGE_SUCCESS';
export const CONVERSATION_SEND_MESSAGE_ERROR = 'CONVERSATION_SEND_MESSAGE_ERROR';
export const CONVERSATION_SEND_MESSAGE_FAILED = 'CONVERSATION_SEND_MESSAGE_FAILED';
export const CONVERSATION_SEND_MESSAGE_ERROR_NETWORK = 'CONVERSATION_SEND_MESSAGE_ERROR_NETWORK';
export const CONVERSATION_SEND_MESSAGE_INPROGRESS = 'CONVERSATION_SEND_MESSAGE_INPROGRESS';
export const CONVERSATION_ACTIVATE_FETCHING = 'CONVERSATION_ACTIVATE_FETCHING';
export const CONVERSATION_ON_FOCUS = 'CONVERSATION_ON_FOCUS';
export const CONVERSATION_PUSH_LOCAL_NEW_MESSAGE = 'CONVERSATION_PUSH_LOCAL_NEW_MESSAGE';
export const CONVERSATION_UPDATE_STATUS_MESSAGE = 'CONVERSATION_UPDATE_STATUS_MESSAGE';
export const CONVERSATION_RESET_BADGE = 'CONVERSATION_RESET_BADGE';
export const CONVERSATION_SET_RELOAD = 'CONVERSATION_SET_RELOAD';
export const CONVERSATION_UPDATE_STATUS_READ = 'CONVERSATION_UPDATE_STATUS_READ';
export const CONVERSATION_PUSH_NEW_CHAT = 'CONVERSATION_PUSH_NEW_CHAT';
export const CONVERSATION_FETCH_ALL_EACH_INPROGRESS = 'CONVERSATION_FETCH_ALL_EACH_INPROGRESS';
export const CONVERSATION_FETCH_ALL_EACH_FINISH = 'CONVERSATION_FETCH_ALL_EACH_FINISH';
export const CONVERSATION_DELETE_MESSAGE_INPROGRESS = 'CONVERSATION_DELETE_MESSAGE_INPROGRESS';
export const CONVERSATION_DELETE_MESSAGE_SUCCESS = 'CONVERSATION_DELETE_MESSAGE_SUCCESS';
export const CONVERSATION_RESET_GROUP_BADGE = 'CONVERSATION_RESET_GROUP_BADGE';
export const CONVERSATION_UPDATE_STATUS_READ_PER_MESSAGE_GROUP = 'CONVERSATION_UPDATE_STATUS_READ_PER_MESSAGE_GROUP';
export const CONVERSATION_DELETE_FRIENDCHAT = 'CONVERSATION_DELETE_FRIENDCHAT';

//  MESSAGE
export const MESSAGE_READ_INPROGRESS = 'MESSAGE_READ_INPROGRESS';
export const MESSAGE_READ_SUCCESS = 'MESSAGE_READ_SUCCESS';
export const MESSAGE_READ_ERROR = 'MESSAGE_READ_ERROR';

// CONTACTS
export const CONTACTS_FETCH_ALL_FAILED = 'CONTACTS_FETCH_ALL_FAILED';
export const CONTACTS_FETCH_ALL_SUCCESS = 'CONTACTS_FETCH_ALL_SUCCESS';
export const CONTACTS_FETCH_ALL_INPROGRESS = 'CONTACTS_FETCH_ALL_INPROGRESS';

export const CONTACTS_FETCH_ONCE_FAILED = 'CONTACTS_FETCH_ONCE_FAILED';
export const CONTACTS_FETCH_ONCE_SUCCESS = 'CONTACTS_FETCH_ONCE_SUCCESS';
export const CONTACTS_FETCH_ONCE_INPROGRESS = 'CONTACTS_FETCH_ONCE_INPROGRESS';

export const CONTACTS_SAVE_LOCAL = 'CONTACTS_SAVE_LOCAL';
export const CONTACTS_FETCH_ALL_RAYAKU_SUCCESS = 'CONTACTS_FETCH_ALL_RAYAKU_SUCCESS';
export const CONTACTS_FETCH_ALL_NONRAYAKU_SUCCESS = 'CONTACTS_FETCH_ALL_NONRAYAKU_SUCCESS';
export const CONTACTS_GET_ALL_INPROGRESS = 'CONTACTS_GET_ALL_INPROGRESS';
export const CONTACTS_GET_ALL_FAILED = 'CONTACTS_GET_ALL_FAILED';
export const CONTACTS_SET_RELOAD = 'CONTACTS_SET_RELOAD';
export const CONTACTS_PUSH_INPROGRESS = 'CONTACTS_PUSH_INPROGRESS';
export const CONTACTS_PUSH_FINISH = 'CONTACTS_PUSH_FINISH';
export const CONTACTS_UPDATE_STATUS_RAYAKU = 'CONTACTS_UPDATE_STATUS_RAYAKU';

// SESSION
export const SESSION_UPDATE = 'SESSION_UPDATE';
export const SESSION_UPDATE_APP_STATE = 'SESSION_UPDATE_APP_STATE';
export const SESSION_EXIT_PROPER = 'SESSION_EXIT_PROPER';
export const SESSION_SET_VERSION = 'SESSION_SET_VERSION';
export const SESSION_UPDATE_DISPLAY_NAME = 'SESSION_UPDATE_DISPLAY_NAME';
export const SESSION_UPDATE_PROFILE_PICTURE = 'SESSION_UPDATE_PROFILE_PICTURE';

// GROUPPROFILE
export const GROUPPROFILE_CREATE_ERROR = 'GROUPPROFILE_CREATE_ERROR';
export const GROUPPROFILE_CREATE_SUCCESS = 'GROUPPROFILE_CREATE_SUCCESS';
export const GROUPPROFILE_CREATE_INPROGRESS = 'GROUPPROFILE_CREATE_INPROGRESS';
export const GROUPPROFILE_UPDATE_INPROGRESS = 'GROUPPROFILE_UPDATE_INPROGRESS';
export const GROUPPROFILE_UPDATE_SUCCESS = 'GROUPPROFILE_UPDATE_SUCCESS';
export const GROUPPROFILE_UPDATE_PHOTO_INPROGRESS = 'UGROUPPROFILE_UPDATE_PHOTO_INPROGRESS';
export const GROUPPROFILE_UPDATE_PHOTO_SUCCESS = 'GROUPPROFILE_UPDATE_PHOTO_SUCCESS';
export const GROUPPROFILE_UPDATE_ERROR = 'GROUPPROFILE_UPDATE_ERROR';
export const GROUPPROFILE_ONCHANGE_GROUPNAME = 'GROUPPROFILE_ONCHANGE_GROUPNAME';
export const GROUPPROFILE_ONCHANGE_GROUPPICTURE = 'GROUPPROFILE_ONCHANGE_GROUPPICTURE';
export const GROUPPROFILE_CLEAR_FORM_CREATEGROUP = 'GROUPPROFILE_CLEAR_FORM_CREATEGROUP';
export const GROUPPROFILE_MODAL_GROUPRENAME_TOGGLE = 'GROUPPROFILE_MODAL_GROUPRENAME_TOGGLE';
export const GROUPPROFILE_SET_GROUPID = 'GROUPPROFILE_SET_GROUPID';


// navigation
export const SWITCH_TAB = 'SWITCH_TAB';
export const SWITCH_MENU = 'SWITCH_MENU';

// selection
export const SELECT_EDIT_MODE = 'SELECT_EDIT_MODE';
export const SELECT_PHONE_NUMBER = 'SELECT_PHONE_NUMBER';

// FLAG
export const FLAG_SET_EDITMODE_PER_SCENE = 'FLAG_SET_EDITMODE_PER_SCENE';
export const FLAG_PUSH_OR_POP_SELECTED_ITEM = 'FLAG_PUSH_OR_POP_SELECTED_ITEM';

// KEY
export const SELECTED_GROUP_MEMBERS_KEY = 'SELECTED_GROUP_MEMBERS_KEY'; // for create new group
export const SELECTED_EXISTING_GROUP_MEMBERS_KEY = 'SELECTED_EXISTING_GROUP_MEMBERS_KEY'; // used for add new greoup member
export const SELECTED_CHATS_KEY = 'SELECTED_CHATS_KEY'; // for edit chat list

// group
export const SELECT_GROUP_MEMBER_SUCCESS = 'SELECT_GROUP_MEMBER_SUCCESS';

// URL
export const URL_RAYAKU = 'http://rayaku.id';

// SHARE MESSAGE
export const MESSAGE_SHARE = 'Enjoy chatting through Rayaku here! ';
export const TITLE_SHARE = 'Share Rayaku to your friends: ';

// CONTACT TYPE
export const CONTACT_TYPE_MOBILE = 'MOBILE';
export const CONTACT_TYPE_INVITE = 'INVITE';

// ENTITY
export const ENTITY_GROUP = 'ENTITY_GROUP';
export const ENTITY_USER = 'ENTITY_USER';

// MESSAGE ITEMS
export const ITEMS_CHAT = [
  'Mark As Read',
  'Pin Conversation',
  'Archive',
  'Delete',
  'Mute',
  'Cancel'
];

export const ITEMS_MESSAGE = [
  'Edit',
  'Cancel'
];

// IMAGEPICKER ITEMS
export const ITEMS_IMAGE_PICKER = [
  'Take Photo',
  'Choose from Gallery',
  'Cancel'
];

// GROUP MEMBER ITEMS
export const ITEMS_GROUP_MEMBERS = [
  'Delete',
  'Cancel'
];
