# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PizzaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for PizzaApp
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  # pod 'FacebookSDK' 
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  pod 'Google-Mobile-Ads-SDK'

  pod 'XCDYouTubeKit', '~> 2.5'

  # target 'PizzaApp-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  # pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  # pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  # pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

  # pod 'react-native-video', :path => '../node_modules/react-native-video'

  # target 'PizzaAppTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

target 'PizzaApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PizzaApp-tvOS

  target 'PizzaApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
