# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PizzaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for PizzaApp
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/AdMob', '~> 6.3.0'

  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  # pod 'FacebookSDK' 
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  # pod 'Google-Mobile-Ads-SDK'

  pod 'XCDYouTubeKit', '~> 2.5'

  # target 'PizzaApp-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  # pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  # pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  # pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'

  # pod 'react-native-video', :path => '../node_modules/react-native-video'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  # target 'PizzaAppTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end
end

target 'PizzaApp-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PizzaApp-tvOS

  target 'PizzaApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# post_install do |installer|
#   rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
#   rnfirebase.build_configurations.each do |config|
#     config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
#   end
# end
