// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),

  headerBar: require('../Images/header_bar.png'),
  hamburgerMenu: require('../Images/menu/hamburger_menu.png'),
  backWhite: require('../Images/back_white.png'),
  headerHome: require('../Images/home/home.png'),
  searchWhite: require('../Images/search_white/search.png'),
  bg: require('../Images/bg1.png'),
  drawerCover: require('../Images/drawer-cover.png'),
  drawerImage: require('../Images/logo-kitchen-sink.png'),
  movieIcon: require('../Images/movieIcon.png'),
  sdabooksIcon: require('../Images/sdabooksicon.png'),
  powerpointIcon: require('../Images/powerpointicon.png'),
  launchscreenBg: require('../Images/launchscreen-bg.png'),
  launchscreenLogo: require('../Images/logo-kitchen-sink.png'),
  menufaces: require('../Images/menu/faces.png'),
  defaultImageBanner: require('../Images/default_image/banner/banner.png'),
  defaultImageBannerLandscape: require('../Images/default_image/banner_landscape/banner_landscape.png'),
  defaultImageCarousal: require('../Images/default_image/carousal/carousal.png'),
  liveIcon: require('../Images/live_icon/live.png'),
  upcomingIcon: require('../Images/upcoming_icon/upcoming.png'),
  replayIcon: require('../Images/replay_icon/replay.png'),
  freeIcon: require('../Images/free_icon/free.png'),
  nextArrow: require('../Images/next_arrow/next_arrow.png'),
  info: require('../Images/info.png'),
  chevronRight2: require('../Images/chevron_right.png'),
  landingPageBan: require('../Images/landingPageBanner.png'),
  globe: require('../Images/globe.png'),
  logoBayar2: require('../Images/bayar2.png')
}

export default images
